import mongoose from 'mongoose';
import { beforeAll, describe, expect, it } from 'vitest';
import { Cart, Category, Collection, DeliveryOption, Order, Product, Review, User, WishlistItem } from '../src/models';
import { cartFixture, categoryFixture, collectionFixture, deliveryOptionFixture, orderFixture, productFixture, reviewFixture, userFixture, wishlistItemFixture } from './fixtures/models';
beforeAll(async () => { await Promise.all([User, Product, Category, Collection, Review, Cart, WishlistItem, Order, DeliveryOption].map((m) => m.syncIndexes())); });
describe('Phase 2 models', () => {
 it('registers every model once', async () => { expect(Object.keys(mongoose.models).sort()).toEqual(['Cart','Category','Collection','DeliveryOption','Order','Product','Review','User','WishlistItem'].sort()); await expect(import('../src/models/index.js')).resolves.toBeDefined(); });
 it('enforces required fields and enums', async () => { await expect(new User({}).validate()).rejects.toThrow(); await expect(new Product(productFixture({ genderCollection: 'kids' })).validate()).rejects.toThrow(); await expect(new Review(reviewFixture({ fitFeedback: 'perfect' })).validate()).rejects.toThrow(); await expect(new Order(orderFixture({ status: 'shipped', paymentStatus: 'authorised' })).validate()).rejects.toThrow(); });
 it('applies defaults', () => { const u = new User(userFixture()); const p = new Product(productFixture()); expect([u.role,u.isActive,p.isPublished,p.rating]).toEqual(['customer',true,false,0]); });
 it('rejects invalid numbers and sale prices', async () => { await expect(new Product(productFixture({ price: -1 })).validate()).rejects.toThrow(); await expect(new Product(productFixture({ salePrice: 101 })).validate()).rejects.toThrow(); await expect(new Product(productFixture({ variants: [{ sku:'NEG',colour:'Black',colourHex:'#000',size:'M',stock:-1 }] })).validate()).rejects.toThrow(); await expect(new Review(reviewFixture({ rating: 6 })).validate()).rejects.toThrow(); await expect(new Cart(cartFixture({ items: [{ productId:new mongoose.Types.ObjectId(),variantId:new mongoose.Types.ObjectId(),colour:'Black',size:'M',quantity:0,price:10 }] })).validate()).rejects.toThrow(); });
 it.each([['email',User,()=>userFixture({email:'DUP@example.com'}),()=>userFixture({email:'dup@example.com'})],['product slug',Product,()=>productFixture({slug:'duplicate-product'}),()=>productFixture({slug:'duplicate-product'})],['category slug',Category,()=>categoryFixture({slug:'duplicate-category'}),()=>categoryFixture({slug:'duplicate-category'})],['collection slug',Collection,()=>collectionFixture({slug:'duplicate-collection'}),()=>collectionFixture({slug:'duplicate-collection'})]])('rejects duplicate %s', async (_n,Model,first,second) => { await Model.create(first()); await expect(Model.create(second())).rejects.toMatchObject({code:11000}); });
 it('enforces wishlist uniqueness', async () => { const x=wishlistItemFixture(); await WishlistItem.create(x); await expect(WishlistItem.create(x)).rejects.toMatchObject({code:11000}); });
 it('serialises ids, embedded ids and dates', async () => { const u=await User.create(userFixture({addresses:[{label:'Home',firstName:'Ada',lastName:'Lovelace',line1:'1 Road',city:'London',postcode:'sw1a 1aa',country:'UK'}]})); const j=u.toJSON() as Record<string, any>; expect(typeof j.id).toBe('string'); expect(j._id).toBeUndefined(); expect(j.__v).toBeUndefined(); expect(typeof j.createdAt).toBe('string'); expect(typeof j.addresses[0].id).toBe('string'); });
 it('uses references and order snapshots', () => { const c=new Cart(cartFixture()), w=new WishlistItem(wishlistItemFixture()), o=new Order(orderFixture()); expect(c.items[0]?.productId).toBeInstanceOf(mongoose.Types.ObjectId); expect(w.productId).toBeInstanceOf(mongoose.Types.ObjectId); expect(o.items[0]?.productName).toBe('Wool Coat'); });
 it('validates exclusive owner identities', async () => { await expect(new Cart(cartFixture({userId:undefined,guestId:undefined})).validate()).rejects.toThrow(); await expect(new Order(orderFixture({guestEmail:'guest@example.com'})).validate()).rejects.toThrow(); });
 it('provides valid core factories', async () => { await expect(new Category(categoryFixture()).validate()).resolves.toBeUndefined(); await expect(new Collection(collectionFixture()).validate()).resolves.toBeUndefined(); await expect(new DeliveryOption(deliveryOptionFixture()).validate()).resolves.toBeUndefined(); });
});
